In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
arr = np.ones((3,4))

In [5]:
arr.dtype

dtype('float64')

In [6]:
arr.shape

(3, 4)

In [7]:
np.empty((2,2))

array([[0.00000000e+000, 2.22525176e+088],
       [4.08147142e-315, 0.00000000e+000]])

In [8]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
# 대각선 기준 위로 1단계
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
# 대각선 기준 아래로 2단계
np.eye(3, k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [17]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [18]:
# endpoint=False: 끝나는 값 3.0을 포함하지 않고 균등하게
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [12]:
# arrange()
# 범위: [시작, 끝)
# 입력값이 3개일 때: 시작, 끝, 간격
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
arr.shape

(5,)

In [14]:
np.arange(3,7)

array([3, 4, 5, 6])

In [15]:
np.arange(3, 9, 2)

array([3, 5, 7])

In [19]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr.shape

(3, 4)

In [24]:
# -1을 입력해 다차원 배열을 1차원으로
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# ravel(): 다차원 배열을 1차원으로
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
# reshape(-1, 1): -1은 행, 1은 열. 즉, 행은 -1로 알 수 없고, 1열인 배열을 생성
arr.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [28]:
# reshape(3, -1): 열은 -1로 알 수 없지만, 3개의 행으로 된 배열을 생성
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# 3차원 배열: 2는 면, 3은 행, 4는 열
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
arr.ndim

3

In [32]:
arr.size

24

In [33]:
arr.dtype

dtype('int64')

In [34]:
arr.itemsize

8

In [35]:
arr.strides

(96, 32, 8)